### ISSUE TITLE
Activation key registration fails if system is already registered

### ISSUE THREAD

**Issue by briansmith0** [linux-system-roles/rhc#90]
I'm using the rhc system role to register a system using an activation key.  When I run the playbook the first time, it succeeds and successfully registers the system.  

If I run the playbook again, it fails the second time with an error:

TASK [redhat.rhel_system_roles.rhc : Call subscription-manager] **********************************************************************************************
fatal: [rhel8-server2.example.com]: FAILED! => {"changed": false, "msg": "parameters are mutually exclusive: activationkey|username"}

Example playbook I'm using:
```yaml
- name: Run system roles
  hosts: all
  become: true
  tasks: 
    - name: run rhc system role
      include_role:
        name: redhat.rhel_system_roles.rhc
      vars:
        rhc_state: present
        rhc_auth:
          activation_keys:
            keys: 
              - "<redacted>"
        rhc_organization: "<redacted>"

```
